### ISSUE TITLE
Updates to the Supporter Handbook

### ISSUE THREAD

**Issue by efuaakum** [cbfacademy/supporter-handbook#1]
Some additions to the supporter handbook have been suggested below, please review the suggestion:

**Instructors Page:** 

**During the Session**
- Keep your camera on throughout the session

**Anything Else**
- You will be expected to attend all sessions and provide a minimum of 48 hours' notice if unable to attend
- Payment is given only for sessions you attend. No payment can given for missed sessions due to sickness or other reasons

**Teaching Assistants Page:**

**During the Session**
- Keep your camera on throughout the session

**Anything Else**
- Payment is given only for sessions you attend. No payment can given for missed sessions due to sickness or other reasons 
- You will be expected to attend all sessions and provide a minimum of 48 hours' notice if unable to attend

**Comment by sohbaker** [comment]
Sounds fine to me. A couple of additional suggestions: 

- reword the "attend all sessions" slightly to say that they're expected to attend all sessions that they've been scheduled for. 

- minimum of 48 hours to allow us time to arrange cover. If they are able to support with arranging cover within the instructor team that would be appreciated (there's probably a better way to word that) 

- just to check, are we telling supporters about payment terms when we confirm the rate with them? Just thinking there should be more than one place that we make it clear that they are only paid for sessions that they attend. 

@efuaakum Let me know what you think. Happy to edit the wiki once agreed

**Comment by efuaakum** [comment]
Thanks @sohbaker, I'm happy with the rewording. Please make the updates to the wiki.

Regarding payment terms, yes, they are usually shared via email and communicated during onboarding by HR. It will be great to have them in the wiki too.

**Comment by sohbaker** [comment]
Edits completed on Instructor and Teaching Assistant pages.
